[package]
name = "wizards-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
form_urlencoded = "1.0"
json = "0.12.4"
signal-hook = "0.3.13"
tiny_http = "0.11.0"
once_cell = "1.10"
regex = { version = "1.5", default-features = false, features = ["std"] }
url = "2.2" # should match tiny_http
